apiVersion: batch/v1
kind: Job
metadata:
  name: fibonacci-job
spec:
  template:
    spec:
      containers:
      - name: fibonacci-load
        image: errm/ab
        args: ["-n$(REQUESTS)", "-c$(CONCURRENCY)", "$(JOB_TARGET_URL)"]
        env:
        - name: REQUESTS
          value: "##REQUESTS##"
        - name: CONCURRENCY
          value: "##CONCURRENCY##"
        - name: JOB_TARGET_URL
          value: "##JOB_TARGET_URL##"
      restartPolicy: OnFailure